### ISSUE TITLE
Add support for custom queries 

### ISSUE THREAD

**Issue by dzhelezov** [subsquid/hydra#19]
For many users, it is critical to be able to extend the functionality provided by `hydra-cli typegen` with custom queries. One typically would add resolvers extending the generated sources. We should introduce a way to easily add new resolvers and make sure `codegen` never rewrites the custom code.

**Comment by olegvg** [comment]
So resolving this issue leads us to many-to-many/subquery query approach, isn't it?

**Comment by dzhelezov** [comment]
Yeah pretty much any ad-hoc sql query can be supported and turned into a GraphQL query

**Comment by dzhelezov** [comment]
Introduced in v4
