### ISSUE TITLE
07/13 - Provide united cli interface for new non-monorepo project structure

### ISSUE THREAD

**Issue by FlaPS** [subsquid/hydra#32]
Combile cli packages interfaces:

- hydra-cli,
- hydra-typegen
- hydra-indexer
- hydra-processor

into one cli's entry point

**Comment by olegvg** [comment]
let's start with the proper conversion from `hydra-{cli|hydra-cli|indexer|processor}` to
```
hydra cli
hydra typegen
hydra indexer
hydra processor
```
So commands -> subcommand -> args
