### ISSUE TITLE
Release v4

### ISSUE THREAD

**Issue by eldargab** [subsquid/hydra#69]
It's time to release v4. Below is a TODO list for release

- [ ] Publish our warthog fork to npm
- [x] #37 
- [ ] Deside on `ts-node` usage
- [ ] Make `entities`, `mappings.imports` sections of `manifest.yml` optional
- [ ] Add `hydra-cli db:drop`, `hydra-cli db:revert`
- [ ] Delete documentation from the main repo
- [ ] Run over documentation to ensure it is up to date

**Comment by dzhelezov** [comment]
Also ensure all the indexers are in sync with v4 available

**Comment by dzhelezov** [comment]
- Add `hydra-cli db:drop` ?

**Comment by eldargab** [comment]
> * Add `hydra-cli db:drop` ?

Yes, added to TODO list
